import os
import datetime

def save_document(response_text: str, directory: str = "./output"):
    """Export travel plan to Markdown file with proper formatting"""
    try:
        # Create absolute path for better reliability
        abs_directory = os.path.abspath(directory)
        os.makedirs(abs_directory, exist_ok=True)
        print(f"Directory created/exists: {abs_directory}")
        
        # Create markdown content with metadata header
        markdown_content = f"""# 🌍 AI Travel Plan

**Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  
**Created by:** Trip Planner AI

---

{response_text}

---

*This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
"""
                
        # Generate timestamp-based filename
        timestamp = datetime.datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
        filename = os.path.join(abs_directory, f"AI_Trip_Planner_{timestamp}.md")

        print(f"Attempting to save file: {filename}")

        # Write to markdown file with UTF-8 encoding
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(markdown_content)
        
        print(f"✅ Markdown file saved successfully: {filename}")
        return filename
        
    except Exception as e:
        print(f"❌ Error saving markdown file: {e}")
        return None